#!/bin/sh

################################################################################
#    Copyright (c) 2017, 2018 Eurotech
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
################################################################################

# Configure credentials

: ARTEMIS_USER=${ARTEMIS_USER:=kapua-sys}
: ARTEMIS_PASS=${ARTEMIS_PASS:=kapua-password}

ls -al /opt/artemis

sh
#/opt/artemis/bin/artemis user add --user ${ARTEMIS_USER} --password ${ARTEMIS_PASS} --role amq

# Continue with startup

exec /opt/artemis/bin/artemis create \
    --allow-anonymous \
    --autocreate \
    --cluster-password password \
    --cluster-user user \
    --clustered false \
    --data ./data/kapua --default-port 1883 \
    --disable-persistence false \
    --home /usr/local/artemis \
    --host ${BINDING_IP} \
    --name kapua \
    --password password \
    --allow-anonymous \
    --user user \
    --verbose kapua

exec /opt/artemis/bin/artemis run xml:${ARTEMIS_CONFIGURATION}/bootstrap.xml