#!/bin/sh
################################################################################
#    Copyright (c) 2020 Eurotech and/or its affiliates and others
#
#    All rights reserved. This program and the accompanying materials
#    are made available under the terms of the Eclipse Public License v1.0
#    which accompanies this distribution, and is available at
#    http://www.eclipse.org/legal/epl-v10.html
#
#    Contributors:
#        Eurotech
################################################################################

#remote debugging
#-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=y

java ${JAVA_OPTS} -Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=8001,suspend=n -jar kapua-consumer-lifecycle-1.3.0-EXT-CONN-SNAPSHOT-uber.jar