#*******************************************************************************
# Copyright (c) 2011, 2019 Eurotech and/or its affiliates and others
#
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     Eurotech - initial API and implementation
#     Red Hat Inc
#*******************************************************************************

# Vagrant 1.9.6 or major is required
# since one of the previous version had a bug with Centos/7 box
Vagrant.require_version ">= 1.9.6"

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_check_update = false

  # If Virtualbox provider
  # Check that vagrant-vbguest plugin is installed
  # If missing, install it.
  config.vm.provider "virtualbox" do |vb|
    unless Vagrant.has_plugin?("vagrant-vbguest")
      system('if ! vagrant plugin list | grep -q vagrant-vbguest; then echo "Installing missing plugin: vagrant-vbguest" ;vagrant plugin install vagrant-vbguest; fi')
    end
  end

  config.vm.provision "shell", inline: <<-SHELL
    export DEBIAN_FRONTEND=noninteractive

    export ELASTICSEARCH_VERSION="5.4.0"
    export H2DB_VERSION="1.4.192"
    export ARTEMIS_VERSION="2.8.1"
    export JETTY_VERSION="9.4.12.v20180830"

    export BINDING_IP="192.168.33.10"

    #############################
    ### Install OpenJDK 8     ###
    #############################
    sudo yum clean all
    sudo yum install -y java-1.8.0-openjdk-devel

    #############################
    ### Install Artemis       ###
    #############################
    cd /usr/local/
    sudo curl -O https://archive.apache.org/dist/activemq/activemq-artemis/${ARTEMIS_VERSION}/apache-artemis-${ARTEMIS_VERSION}-bin.tar.gz
    sudo tar zxvf apache-artemis-${ARTEMIS_VERSION}-bin.tar.gz
    sudo rm apache-artemis-${ARTEMIS_VERSION}-bin.tar.gz
    ln -s apache-artemis-${ARTEMIS_VERSION} artemis

    cd artemis
    rm -rf examples

    #create server event
    ./bin/artemis create \
    --allow-anonymous \
    --autocreate \
    --cluster-password password \
    --cluster-user user \
    --clustered false \
    --data ./data/kapua-event --default-port 61616 \
    --disable-persistence false \
    --home /usr/local/artemis \
    --host ${BINDING_IP} \
    --name kapua-event \
    --password password \
    --allow-anonymous \
    --user user \
    --verbose kapua-event

    #create server telemetry
    ./bin/artemis create \
    --allow-anonymous \
    --autocreate \
    --cluster-password password \
    --cluster-user user \
    --clustered false \
    --data ./data/kapua-telemetry --default-port 1883 \
    --disable-persistence false \
    --home /usr/local/artemis \
    --host ${BINDING_IP} \
    --name kapua-telemetry \
    --password password \
    --allow-anonymous \
    --user user \
    --verbose kapua-telemetry

    #############################
    ### Install H2            ###
    #############################
    sudo mkdir -p /usr/local/h2-${H2DB_VERSION}
    cd /usr/local/h2-${H2DB_VERSION}
    sudo curl -O http://repo2.maven.org/maven2/com/h2database/h2/${H2DB_VERSION}/h2-${H2DB_VERSION}.jar
    cd ../
    ln -s h2-${H2DB_VERSION} h2

    #############################
    ### Install Elasticsearch ###
    #############################
    # Install Elasticsearch
    cd /usr/local/
    sudo curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz
    sudo tar -xvf elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz
    sudo rm elasticsearch-${ELASTICSEARCH_VERSION}.tar.gz
    sudo ln -s elasticsearch-${ELASTICSEARCH_VERSION} elasticsearch

    #############################
    ### Install Jetty         ###
    #############################
    cd /usr/local/
    curl -s https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-distribution/${JETTY_VERSION}/jetty-distribution-${JETTY_VERSION}.tar.gz -o jetty-distribution.tar.gz
    sudo tar zxvf jetty-distribution.tar.gz
    sudo rm jetty-distribution.tar.gz
    ln -s jetty-distribution-${JETTY_VERSION} jetty

    cd jetty
    mkdir -p lib/ext /var/lib/jetty/start.d /var/lib/jetty/modules

    cd /var/lib/jetty/modules
    curl -O https://raw.githubusercontent.com/jetty-project/logging-modules/master/capture-all/logging.mod
    curl -O https://raw.githubusercontent.com/jetty-project/logging-modules/master/centralized/webapp-logging.mod

    cd /usr/local/jetty
    java -jar start.jar --approve-all-licenses --create-startd --add-to-start=http,jsp,jstl,websocket,deploy,logging,webapp-logging,jmx,stats -Djetty.base=/var/lib/jetty

    sudo chown -R vagrant /usr/local/jetty/
    sudo chown -R vagrant /var/lib/jetty

    #############################
    ### System Configuration  ###
    #############################
    sudo bash -c 'echo "* soft nofile 65536" > /etc/security/limits.d/kapua.conf'
    sudo bash -c 'echo "* hard nofile 65536" >> /etc/security/limits.d/kapua.conf'

    sudo bash -c "echo 'vm.max_map_count=262144' > /etc/sysctl.d/98-kapua.conf"
    sudo sysctl --system

    cat /dev/null > ~/.bash_history && history -c
  SHELL
end
